var team24 = [
  [
    {
      name: "Prof. Priyanka Ghosh",
      post: "HOD",
      fb: "https://www.facebook.com/profile.php?id=100005799362676",
      insta: "https://www.instagram.com/govind_gupta_46/",
      linkedin:
        "https://www.linkedin.com/in/priyanka-ghosh-33173314/?originalSubdomain=in",
      website: "https://iitk.ac.in/new/priyanka-ghosh",
      mail: "mailto:priyog@iitk.ac.in",
      image: "/team/team23/priyanka-ghosh-iitk.jpg",
    },
    {
      name: "Prof. Chunendra Sahu",
      post: "Faculty Adivsor",
      fb: "https://www.facebook.com/profile.php?id=100005799362676",
      insta: "https://www.instagram.com/govind_gupta_46/",
      linkedin: "https://www.linkedin.com/in/chunendra-k-sahu-b90aa33a",
      website: "https://www.iitk.ac.in/new/chunendra-k-sahu",
      mail: "mailto:cksahu@iitk.ac.in",
      image: "/team/team23/cksahu.jpg",
    },
  ],
  [
    {
      id: "1",
      name: "Pranay Saxena",
      post: " Events",
      fb: "https://www.facebook.com/profile.php?id=100006906991000&mibextid=ZbWKwL",
      insta: "https://www.instagram.com/pranay_s22/",
      linkedin: "https://www.linkedin.com/in/pranay-saxena-0971aa258/",
      mail: "mailto:pranays22@iitk.ac.in",
      image: "/team/team23/Pranay_events.jpg",
    },
    {
      id: "2",
      name: "Sahil Arolia",
      post: " Web ",
      fb: " ",
      insta: "https://instagram.com/sahil_arolia?igshid=ZDc4ODBmNjlmNQ== ",
      linkedin: "https://www.linkedin.com/in/sahil-arolia-1a2bb8259",
      mail: "mailto:asahil22@iitk.ac.in",
      image: "/team/team23/Sahil Arolia.jpg",
    },
    {
      id: "4",
      name: "Deepesh Maurya",
      post: " Web ",
      fb: "https://www.facebook.com/dipesh.maurya.940",
      insta: "https://instagram.com/djshakya_?igshid=NGExMmI2YTkyZg==",
      linkedin: "http://www.linkedin.com/in/deepesh-maurya-386486251",
      mail: "mailto:deepeshm22@iitk.ac.in",
      image: " /team/team23/WebDev_Deepesh.jpg",
    },
    {
      id: "3",
      name: "Kuldeep",
      post: " Desgin ",
      fb: " ",
      insta: "https://instagram.com/kuldeep_0_555?igshid=ZDc4ODBmNjlmNQ==",
      linkedin: "https://www.linkedin.com/in/kuldeep-singh-76295b256",
      mail: "mailto:kuldeepb22@iitk.ac.in",
      image: "/team/team23/WebDev_Kuldeep.jpeg",
    },
    {
      id: "5",
      name: "Ruthvik Sai Kalahastri",
      post: " Marketing & Finance ",
      fb: "https://www.facebook.com/kalahastriruthvik2005/",
      insta: "https://www.instagram.com/ruthvik_2005_/",
      linkedin: "https://www.linkedin.com/in/ruthvik-sai-kalahastri-525100261/",
      mail: "mailto:ksruthvik22@iitk.ac.in",
      image: "/team/team23/Finance_Ruthwik.jpg",
    },
    {
      id: "6",
      name: "Lokesh Sunda",
      post: "Marketing & Finance ",
      fb: "",
      insta:
        "https://www.instagram.com/lokeshsunda2004?igsh=MXNiZ212dnZyc2J6ZQ==",
      linkedin: "https://www.linkedin.com/in/lokesh-sunda-7b0773260/",
      mail: "mailto:lokeshs22@iitk.ac.in",
      image: "/team/team23/Finance_lokesh.jpg",
    },
    {
      id: "7",
      name: "Devagya Singh Vats",
      post: "Projects and Content ",
      fb: "https://www.facebook.com/profile.php?id=100086680848212",
      insta: "https://www.instagram.com/devagyavats?igsh=bjlqZHFsd3JoNHNp",
      linkedin:
        "https://www.linkedin.com/in/devagya-vats-a30657261?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      mail: "mailto:devagyasv22@iitk.ac.in",
      image: "/team/team23/devagya_dp.jpg",
    },
    {
      id: "8",
      name: "Rithvik L",
      post: "Content and Project  ",
      fb: "https://www.facebook.com/rithvik.lok/",
      insta: "https://www.instagram.com/rithviklok/",
      linkedin: "https://www.linkedin.com/in/rithvik-l-b84231189/",
      mail: "mailto:rithvikl23@iitk.ac.in",
      image: "/team/team23/Rithvik L_content.jpg",
    },
    {
      id: "9",
      name: "Gousia Karishma Syed ",
      post: "Events ",
      fb: "Karishma Syed",
      insta: "https://www.instagram.com/karishma___syed/",
      linkedin: "http://www.linkedin.com/in/gousia-karishma-syed",
      mail: "mailto:sgousia23@iitk.ac.in",
      image: "/team/team23/Gousia_Karishma_Syed__Events.jpg",
    },
    {
      id: "10",
      name: "Bandi Samanvitha",
      post: " Event   ",
      fb: "",
      insta: "",
      linkedin:
        "https://www.linkedin.com/in/samanvitha-bandi-79baa9290?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BVtWS%2BDdCQUOJ0d6XXLT6Rg%3D%3D",
      mail: "mailto:bandis23@iitk.ac.in",
      image: "/team/team23/Bandi Samanvitha_Events.jpg",
    },
  ],
];

module.exports = team24;
